apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    #SSL
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/proxy-request-buffering: "off"
  labels:
    app: <name of the app>
    track: stable
  name: <name of the external svc>
  namespace: <namespace>
spec:
  clusterIP: 
  externalTrafficPolicy: Cluster
  ports:
  - name: https
    nodePort: 
    port: 443
    protocol: TCP
    targetPort: 80
  - name: http
    nodePort: 
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: <name of the app>
    track: stable
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
